name: Build and publish aws s3 dependency

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build and publish an fbpcf/aws-s3-core image for a particular version'
        default: "Run"
      aws_release:
        description: "The aws s3 version to build and publish (e.g. 1.8.177)"
        required: true
        type: string
      os:
        description: "Which os to use. Currently only supports ubuntu"
        required: false
        type: str
        default: "ubuntu"
      os_release: "The os version to use (e.g. 20.04 for ubuntu)"
        required: false
        type: str
        default: "20.04"

env:
  REGISTRY: ghcr.io

jobs:
  permissions:
    contents: read
    packages: write

  ubuntu:
    runs-on: [self-hosted, e2e_test_runner]

    steps:
    - uses: actions/checkout@v2

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: |
        docker build \
        --build-arg os_release=${{ github.event.inputs.os_release }} \
        --build-arg aws_release=${{ github.event.inputs.aws_release }} \
        -t "fbpcf/${{ github.event.inputs.os }}-aws-s3-core:${{ github.event.inputs.aws_release }}" \
        -f "docker/${DOCKER_DIR}/Dockerfile.${{ github.event.inputs.os }}" .

    - name: Tag image
    - run: |
      docker tag fbpcf/${{ github.event.inputs.os }}-aws-s3-core:${{ github.event.inputs.aws_release }} \
      ${{ env.REGISTRY }}/${{ github.repository }}/${{ github.event.inputs.os }}-aws-s3-core:${{ github.event.inputs.aws_release }}

    - name: Publish image
    run: |
      docker push --all-tags ${{ env.REGISTRY }}/${{ github.repository }}/${{ github.event.inputs.os }}-aws-s3-core
