name: Build and publish emp dependency

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build and publish an fbpcf/emp image for a particular version"
        default: "Run"
      emp_release:
        description: "The emp version to build and publish (e.g. 0.2.3)"
        required: true
        type: string
      emp_tool_release:
        description: "The emp-tool version to build and publish (e.g. 0.2.2)"
        required: true
        type: string
      os:
        description: "Which os to use. Currently only supports ubuntu"
        required: false
        type: str
        default: "ubuntu"
      os_release:
        description: "The os version to use (e.g. 20.04 for ubuntu)"
        required: false
        type: str
        default: "20.04"

env:
  REGISTRY: ghcr.io

jobs:
  ubuntu:
    runs-on: [self-hosted, e2e_test_runner]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
          --build-arg os_release=${{ github.event.inputs.os_release }} \
          --build-arg emp_tool_release=${{ github.event.inputs.emp_tool_release }} \
          --build-arg emp_release=${{ github.event.inputs.emp_release }} \
          -t "fbpcf/${{ github.event.inputs.os }}-emp:${{ github.event.inputs.emp_tool_release }}" \
          -f "docker/${DOCKER_DIR}/Dockerfile.${{ github.event.inputs.os }}" .

      - name: Tag image
        run: |
          docker tag fbpcf/${{ github.event.inputs.os }}-emp:${{ github.event.inputs.emp_tool_release }} \
          ${{ env.REGISTRY }}/${{ github.repository }}/${{ github.event.inputs.os }}-emp:${{ github.event.inputs.emp_tool_release }}

      - name: Publish image
        run: |
          docker push --all-tags ${{ env.REGISTRY }}/${{ github.repository }}/${{ github.event.inputs.os }}-emp
