name: Build and publish folly dependency

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build and publish an fbpcf/folly image for a particular version"
        default: "Run"
      folly_release:
        description: "The folly version to build and publish (e.g. 2021.03.29.00)"
        required: true
        type: string
      fmt_release:
        description: "The fmt version to build and publish (e.g. 7.1.3)"
        required: true
        type: string
      os:
        description: "Which os to use. Currently only supports ubuntu"
        required: false
        type: str
        default: "ubuntu"
      os_release:
        description: "The os version to use (e.g. 20.04 for ubuntu)"
        required: false
        type: str
        default: "20.04"

env:
  REGISTRY: ghcr.io

jobs:
  ubuntu:
    runs-on: [self-hosted, e2e_test_runner]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
          --build-arg os_release=${{ github.event.inputs.os_release }} \
          --build-arg folly_release=${{ github.event.inputs.folly_release }} \
          --build-arg fmt_release=${{ github.event.inputs.fmt_release }} \
          -t "fbpcf/${{ github.event.inputs.os }}-folly:${{ github.event.inputs.folly_release }}" \
          -f "docker/folly/Dockerfile.${{ github.event.inputs.os }}" .

      - name: Tag image
        run: |
          docker tag fbpcf/${{ github.event.inputs.os }}-folly:${{ github.event.inputs.folly_release }} \
          ${{ env.REGISTRY }}/${{ github.repository }}/${{ github.event.inputs.os }}-folly:${{ github.event.inputs.folly_release }}

      - name: Publish image
        run: |
          docker push --all-tags ${{ env.REGISTRY }}/${{ github.repository }}/${{ github.event.inputs.os }}-folly
