name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: [self-hosted, e2e_test_runner]

    steps:
    - uses: actions/checkout@v2

    - name: Build fbpcf docker image
      run: |
        ./build-docker.sh -u

    - name: Sanity check fbpcf library
      timeout-minutes: 3
      run: |
        ./run-millionaire-sample.sh -u

    - name: Cleanup
      run: |
        # remove all images
        docker image prune -af

        # stop and remove all containers
        docker kill $(docker ps -q) || echo "No running containers to stop."
        docker rm $(docker ps -a -q) || echo "No containers to delete."
